# Site settings
title_left    : "Michal's "
title_right   : "space" # default: ""
description   : "AI Research"
keywords      : "Artificial Intelligence, Machine learning, Robotics, College admissions, Self-driving vehicles"
url           : https://heiswayi.github.io/thinkspace # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-214156803-1
twitter_username  : "@michal_pandy"
comments_enabled  : true # if enabled (set to true), please provide your disqus_username
disqus_shortname  : "michalpandy"
postshare_enabled : true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Michal Pándy"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude:
  - "gulp"
  - "node_modules"
  - "bower"
  - "bower_components"
  - "config.rb"
  - "src"
  - "Gemfile"
  - "Gemfile.lock"
  - ".rvmrc"
  - ".rbenv-version"
  - "package.json"
  - "gulpfile.js"
  - "README.md"
  - "Rakefile"
  - "changelog.md"
  - "script"
  - "vendor"
  - "thinkspace.gemspec"
